name: Deploy Storybook

on:
  push:
    branches:
      - "develop"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Manual Checkout
      - uses: actions/checkout@v4

      # Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Add Storybook build and deploy to GitHub Pages
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          build_command: npm run storybook:build-wc
          path: storybook-static/web-components
          checkout: false
