name: Deploy Storybook

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # This action does "npm ci" automatically
      - name: Build Storybook and Deploy to GitHub Pages
        id: build-deploy
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          build_command: npm run build && STORYBOOK_ENV=production npm run storybook:build-wc
          path: storybook-static/web-components
          checkout: false
