name: Release or Prepare for Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # Build and Invoke Changesets Action
  # Changesets Action will do:
  # - Create or update release PR if this is not a release commit
  # - Publish to npm if this is a release commit
  # If Changesets Action publishes the package, we will build the Storybook and deploy it to GitHub Pages.
  release:
    name: Release

    runs-on: ubuntu-latest

    timeout-minutes: 10

    permissions:
      contents: read
      pull-requests: read
      issues: read
      packages: write
      id-token: write

    outputs:
      published: ${{ steps.changesets.outputs.published }}

    steps:
      - name: Create App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: app-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure Git User
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.app-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: GITHUB_TOKEN=$GITHUB_ACTIONS_TOKEN npm run changeset-version
          publish: GITHUB_TOKEN=$GITHUB_ACTIONS_TOKEN npm run changeset-publish
          setupGitUser: false
        env:
          HUSKY: 0
          GITHUB_ACTIONS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      # Build Storybook and Upload Pages Artifact
      # This Storybook is a production environment, as it is built at the same time as the package is released.
      - name: Build Storybook (prod)
        if: steps.changesets.outputs.published == 'true'
        run: npm run storybook:build-wc
        env:
          STORYBOOK_ENV: production

      - name: Upload Storybook Pages Artifact (prod)
        if: steps.changesets.outputs.published == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static/web-components

  # Deploy Storybook to GitHub Pages (prod)
  deploy-prod:
    name: Deploy Storybook (prod)

    needs: release
    if: needs.release.outputs.published == 'true'

    runs-on: ubuntu-latest

    timeout-minutes: 10

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
