name: Renovate

on:
  workflow_dispatch:
  schedule:
    # 21:00 JST, 05:00 PST
    - cron: 0 12 * * *

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  # We don't need write permission as commit/push will be performed using GitHub App token.
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Create App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.8
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ steps.app-token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM_COMMIT: "true"
