name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Playwright Version
        id: playwright-version
        run: echo "version=$(jq -r '.packages["node_modules/playwright"].version' package-lock.json)" >> $GITHUB_OUTPUT

      - name: Cache Playwright
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright with dependencies (cache miss)
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Install Playwright dependencies (cache hit)
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Interaction Test
        run: |
          npm run test:interaction
          STORYBOOK_ENV=production npm run test:interaction

      - name: Visual Regression Test
        run: |
          docker compose up -d
          npm run test:visual
          STORYBOOK_ENV=production npm run test:visual
          docker compose down

      - name: Upload VRT Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: VRT-Result-PR${{ github.event.number }}-${{ github.run_number }}-${{ github.run_attempt }}
          path: test-results
          retention-days: 7
