name: Visual Regression Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  visual-regression:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Cache playwright
        id: cache-playwright
        uses: actions/cache@v4
        env:
          cache-name: playwright-cache
        with:
          path: |
            ~/Library/Caches/ms-playwright
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - run: npx playwright install --with-deps
        if: steps.cache-playwright.outputs.cache-hit != 'true'

      - run: npx playwright install-deps
        if: steps.cache-playwright.outputs.cache-hit == 'true'

      - name: Run tests
        run: npm run build && npm run test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Diff Output attempt-${{ github.run_attempt }}
          path: test-results
          retention-days: 7
