name: Visual Regression Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          npm run lint:lit

      - name: Build
        run: npm run build

      - name: Visual Regression Test
        run: |
          docker compose up -d
          npm run test:visual
          docker compose down

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: VRT-Result-PR${{ github.event.number }}-${{ github.run_number }}-${{ github.run_attempt }}
          path: test-results
          retention-days: 7
