name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  # Linting and Interaction Testing
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45-jammy

    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook
        env:
          STORYBOOK_ENV: production

      - name: Interaction Test
        run: |
          npm run test:interaction
          STORYBOOK_ENV=production npm run test:interaction

  # VRT is separated since it's time consuming.
  visual-regression-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45-jammy

    timeout-minutes: 10

    strategy:
      matrix:
        # `npm run test:visual-<framework>`
        framework: [react, wc]
        # `STORYBOOK_ENV=<env>`
        env: [development, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        if: matrix.env == 'production'
        run: npm run build

      - name: Build Storybook
        if: matrix.env == 'production'
        run: npm run build-storybook
        env:
          STORYBOOK_ENV: production

      - name: Visual Regression Test
        run: npm run test:visual-${{ matrix.framework }}
        env:
          STORYBOOK_ENV: ${{ matrix.env }}
          PLAYWRIGHT_NO_CONTAINER: 1

      - name: Upload VRT Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: VRT-Result-PR${{ github.event.number }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ matrix.framework }}-${{ matrix.env }}
          path: test-results
          retention-days: 7
